version: '3.8'

services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


  web:
    build: .
    command: python /djangoForProf/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoForProf
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

volumes:
  postgres_data: